name: CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
concurrency:
  group: ci-tests-${{ github.ref }}-1
  cancel-in-progress: true
jobs:
  ci:
    name: Build, Lint, Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Load SSH key into GitHub for 1Password Python SDK
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.PLOVER_1PASSWORD_PRIVATE_KEY }}

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Install Test, Coverage, Lint, Type Checking Dependencies
        run: |
          pip install pytest pytest-mock pytest-asyncio pylint mypy coverage
          pip install git+ssh://git@github.com/1Password/onepassword-sdk-python.git@v0.1.1

      - name: Run Linter
        run: pylint plover_1password

      - name: Run Type Checker
        run: mypy plover_1password

      - name: Run Tests
        run: pytest

      - name: Run Coverage
        run: |
          coverage run --module pytest
          coverage report --show-missing
